### ISSUE TITLE
Unable to create new tweets locally

### ISSUE THREAD

**Issue by Engineering-Robert** [vinitkumar/node-twitter#102]
I'm running into an error when trying to create a tweet. I'm running the application locally.

![image](https://user-images.githubusercontent.com/16786990/30610680-f72b3d68-9d4c-11e7-95be-06861c9b3d39.png)

**Comment by vinitkumar** [comment]
@Engineering-Robert I think there is an issue with your config. Did you check if all the required keys and all are there. Also, you need mongodb running using `mongod` for it to work.

Sharing my config, this should work for you too.

```
const path = require("path");
const rootPath = path.normalize(__dirname + "/..");

module.exports = {
  development: {
    db: "mongodb://localhost/ntwitter",
    root: rootPath,
    app: {
      name: "Node Twitter"
    },
    github: {
      clientID: "e3930cf94c772ba10ef1",
      clientSecret: "fb1284b1874444a9c0c55c963092f836596ecc56",
      callbackURL: "http://localhost:3000/auth/github/callback"
    }
  },
  test: {
    db: "mongodb://root:volvo76@ds039078.mongolab.com:39078/ntwitter",
    root: rootPath,
    app: {
      name: "Nodejs Express Mongoose Demo"
    },
    github: {
      clientID: "c2e0f478634366e1289d",
      clientSecret: "0bfde82383deeb99b28d0f6a9eac001a0deb798a",
      callbackURL: "http://nitter.herokuapp.com/auth/github/callback"
    }
  },
  production: {
    db: "mongodb://root:volvo76@ds039078.mongolab.com:39078/ntwitter",
    root: rootPath,
    app: {
      name: "Nodejs Express Mongoose Demo"
    },
    github: {
      clientID: "c2e0f478634366e1289d",
      clientSecret: "0bfde82383deeb99b28d0f6a9eac001a0deb798a",
      callbackURL: "http://nitter.herokuapp.com/auth/github/callback"
    }
  }
};
```

**Comment by Engineering-Robert** [comment]
I don't think it's a problem with the config. The issue appears to be with this bit of code in `/node-twitter/app/controllers/tweets.js`

```
exports.create = (req, res) => {
  logAnalytics(req);
  const tweet = new Tweet(req.body);
  tweet.user = req.user;
  tweet.uploadAndSave(req.files.image, err => {
    if (err) {
      res.render("tweets/new", {
        title: "New Tweet",
        tweet: tweet,
        error: err.errors
      });
    } else {
      res.redirect("/");
    }
  });
};
```

`req.files.image` returns `undefined` for me. I've passed in an empty object as the first argument to `tweet.uploadAndSave` and that seems to have solved the issue for now. I'm not sure what `req.files.image` is suppose to contain (is it a URL path to a profile image?).

**Comment by Engineering-Robert** [comment]
Well I guess I'll close this issue since it seems like the fix I implemented isn't causing any other issues.
