### ISSUE TITLE
Reduce amount of pagination that shows

### ISSUE THREAD

**Issue by Engineering-Robert** [vinitkumar/node-twitter#105]
It would be nice to show the first few pages and as well as the last page in the pagination on the Analytics page. Right now, the pagination shows every single page, and it is taking up a lot of room.
I tried to look where the `createPagination` function was defined, but I couldn't find it anywhere! That is the function that is rendering the pagination in the Jade templates.

![image](https://user-images.githubusercontent.com/16786990/30668307-51009f0a-9e28-11e7-94f0-c40afffac42d.png)

**Comment by vinitkumar** [comment]
@Engineering-Robert I agree with your feedback. If I am not wrong, `createPagination` comes from express.js which we are using. I will look into making it better.

**Comment by Engineering-Robert** [comment]
This was resolved in PR #141
