### ISSUE TITLE
Follow/unfollow button doesn't hold state

### ISSUE THREAD

**Issue by robertcoopercode** [vinitkumar/node-twitter#119]
The button doesn't keep track of whether a user follows another person. It also doesn't allow you to unfollow someone. We need to use some sort of pug conditional that checks if the authenticated user already follows the req.user, with the option to unfollow the person.

Would also be good to update the styling of the button so that it has some good padding within the profile summary box.

**Comment by vinitkumar** [comment]
@Engineering-Robert Yes, the functionality is not complete.

**Comment by vinitkumar** [comment]
@Engineering-Robert If you want, you can pick this one up!
