### ISSUE TITLE
Testing Follow features locally

### ISSUE THREAD

**Issue by Engineering-Robert** [vinitkumar/node-twitter#133]
Hey @vinitkumar, how have you been testing the follow feature locally? Do you log in with a different Github account to have 2 local users to test the feature with?

I'm just curious as i'm refactoring code to use Promises and I don't want to do it with the code that is responsible for the follow feature as I can't really test it.

**Comment by vinitkumar** [comment]
@Engineering-Robert I can test the follow feature as I had a backup of old production database, so I had all the users that I can follow.
