### ISSUE TITLE
Some users don't have a username and their analytics aren't logged

### ISSUE THREAD

**Issue by Engineering-Robert** [vinitkumar/node-twitter#138]
I'm not sure why this happens for some users. Maybe they are using are VPN or something that is masking their information? I honestly don't know.

![image](https://user-images.githubusercontent.com/16786990/30814069-2c9193e6-a1dd-11e7-9c13-e3631170f36b.png)

**Comment by vinitkumar** [comment]
Actually, looks like you introduced this bug when you were updating from jade to pug.

```
- var name = tweet.user.name ? tweet.user.name : tweet.user.username
a(href="/users/"+tweet.user._id)= name
```

This is from before, it checks if the name is there, if not finds the username. but a lot user don't fill up the name where as in your pug template, you removed the check altogether.

```
a(href="/users/"+tweet.user._id) #{tweet.user.name} 
```

The above is from your code.

**Comment by Engineering-Robert** [comment]
Oh man, thanks for finding that!
