### ISSUE TITLE
Recent visits on main dashboard not showing 10 last visits

### ISSUE THREAD

**Issue by robertcoopercode** [vinitkumar/node-twitter#160]
![image](https://user-images.githubusercontent.com/16786990/31060422-809710fc-a6e1-11e7-827d-803d09820ee1.png)
This section should display the last 10 visits on the forum.

**Comment by Engineering-Robert** [comment]
@vinitkumar This looks like it's fixed now? Can we close this issue?

**Comment by Engineering-Robert** [comment]
![image](https://user-images.githubusercontent.com/16786990/31835556-fe65765a-b59f-11e7-9084-0a1d079823b3.png)

**Comment by vinitkumar** [comment]
If I am not wrong, this is still buggy and deserve a fix.

**Comment by vinitkumar** [comment]
@irsol Do you want to pick this up?

**Comment by irsol** [comment]
@vinitkumar ok, I will work on this.

**Comment by vinitkumar** [comment]
@irsol Please let me know if you need any help with this or if you something doesn't make sense.
