### ISSUE TITLE
Add user image to tweet comments

### ISSUE THREAD

**Issue by Engineering-Robert** [vinitkumar/node-twitter#169]
Tweets show the user profile picture, hence it also makes sense for the coments to the show the user image as well.

**Comment by vinitkumar** [comment]
There is a trick involved here. We need to add a new field in the tweet schema to accommodate the `commenterPicture`. But without doing the migration for all the tweets, it is not possible to get the images. So for all new tweets picture will be created. For old once, we show a placeholder image for consistency sake.
