### ISSUE TITLE
Use consistent colors throughout the website

### ISSUE THREAD

**Issue by Engineering-Robert** [vinitkumar/node-twitter#170]
Lots of different colours are being used for colours, we should stick to a branded colour palette.

**Comment by vinitkumar** [comment]
What colour palette you suggest? I think we could decide for that in the sass variables and only use them.

**Comment by Engineering-Robert** [comment]
Yes, I'd like to capture all the main colours in Sass variables so they are all in one spot. I'd have to spend some time figuring out a colour palette. I think most of it looks good, but there are currently alot of different colours being used for buttons, and even the text colours are all consistent throughout the website.
