### ISSUE TITLE
Style the error pages

### ISSUE THREAD

**Issue by robertcoopercode** [vinitkumar/node-twitter#172]

**Comment by vinitkumar** [comment]
I added the black on yellow pages to be like that by design. But I think it is more for debug purpose. We should have an alternate error page for non-debug/production mode.

Let me know what you think.

**Comment by Engineering-Robert** [comment]
I was thinking of just styling those 404 and 500 pages in a more pleasing manner. Look at this example of a nice 404 page:

![image](https://user-images.githubusercontent.com/16786990/31823427-228d3d68-b57a-11e7-90e3-c97d1fa6c871.png)
