### ISSUE TITLE
Improve look of login page with a better button for "Login with Github"

### ISSUE THREAD

**Issue by robertcoopercode** [vinitkumar/node-twitter#194]
### User story
What problem is the feauture trying to solve for the user

### Conditions of satisfaction
Define what must be true for the feature to be considered done

### Additonal specifications
Give some extra specifications if needed like screenshots and designs

### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell what should happen

### Actual behaviour
Tell what happens instead

### Client configuration

**Browser:**
**Operating system:**

#### Web server error log

```
Insert your webserver log here
```

**Comment by arshadkazmi42** [comment]
Is this open for grab? I am interested to take this up.

**Comment by arshadkazmi42** [comment]
Is this still required? I am interested to take this up.

**Comment by robertcoopercode** [comment]
It doesn't look too bad at the moment, but it could at least use some seperation between the "Node Twitter" title and the button itself. Feel free to make a PR regarding this.

![image](https://user-images.githubusercontent.com/16786990/44064430-e5978f46-9f32-11e8-9ae7-1335538aea6b.png)

**Comment by arshadkazmi42** [comment]
Ok. I will work on that later today. 👍

**Comment by arshadkazmi42** [comment]
Added PR [#222](https://github.com/vinitkumar/node-twitter/pull/222)
