### ISSUE TITLE
Unable to run application

### ISSUE THREAD

**Issue by j4ysen** [vinitkumar/node-twitter#202]
Unable to get the app to run, due to issues with tweets.js

### Logs
> nwitter@2.0.0 start /Users/jaysen/Documents/Uni/node-twitter
> node server.js

> /Users/user1/Documents/Uni/node-twitter/lib/utils.js:1
> (function (exports, require, module, __filename, __dirname) { /
                                                              ^
> SyntaxError: Invalid regular expression: missing /
>     at Object.exports.runInThisContext (vm.js:76:16)
>     at Module._compile (module.js:542:28)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.require (module.js:497:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/Users/user1/Documents/Uni/node-twitter/app/models/tweets.js:3:15)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.require (module.js:497:17)
>     at require (internal/module.js:20:19)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! nwitter@2.0.0 start: `node server.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the nwitter@2.0.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/user1/.npm/_logs/2017-12-07T10_51_49_739Z-debug.log

### Steps to reproduce
npm start

**Comment by vinitkumar** [comment]
Which node.js version are you running this on? Please add the output of
'node --version'

**Comment by j4ysen** [comment]
v6.9.2

**Comment by vinitkumar** [comment]
Okay. This seems to be the cause of the issue. Upgrade your node.js (https://nodejs.org/en/) to at least `8.9.2` or `9.2.0`. The code here is based on latest ES6 based code that is not supported on an old version of Node.js and I don't support old versions of them.  So upgrade node.js and run the code again following the instructions from the readme (https://github.com/vinitkumar/node-twitter#usage).  If you still face any issues, let me know.
