### ISSUE TITLE
Integrate firebase

### ISSUE THREAD

**Issue by vinitkumar** [vinitkumar/node-twitter#210]
Firebase could be used for messaging, image upload etc. Let's look into the possibility of using it.

@Engineering-Robert Let me know what you think about this.

https://firebase.google.com/docs/admin/setup

**Comment by Engineering-Robert** [comment]
Not sure it's worth rewriting everything over to firebase. I think time can be better spend on other features since the current Mongo database solution seems to be sufficient at the moment.
