### ISSUE TITLE
App won't run after authentication - clean install

### ISSUE THREAD

**Issue by sparra1000** [vinitkumar/node-twitter#215]
Installed this from the download.  Created an app in github for credentials.  After authenticating the page doesn't load and I get this error in the Windows Command Console where 'npm start' was run.

Running node 8.11.1, nvm 5.6.0

Here is the output:
D:\TwitterClone\node-twitter-master\node-twitter-master>npm start

> nwitter@2.1.0 start D:\TwitterClone\node-twitter-master\node-twitter-
master
> nodemon server.js

[nodemon] 1.17.3
[nodemon] to restart at any time, enter 'rs'
[nodemon] watching: *.*
[nodemon] starting `node server.js`
raven@2.6.0 alert: no DSN provided, error reporting disabled
Express app started on port 3000
TypeError: Cannot read property 'createdAt' of null
    at D:\TwitterClone\node-twitter-master\node-twitter-master\config\m
iddlewares\logger.js:15:30
    at D:\TwitterClone\node-twitter-master\node-twitter-master\node_mod
ules\mongoose\lib\query.js:3118:18
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by vinitkumar** [comment]
Hey, @sparra1000. Looks like there is a bug in the code for the logger. I will push a fix for it.

**Comment by vinitkumar** [comment]
@sparra1000 Alright, I pushed the fix to master branch. Pull the latest master branch and it should just work.

**Comment by sparra1000** [comment]
Thanks it works now.
