### ISSUE TITLE
TypeError: Cannot set property 'github' of null

### ISSUE THREAD

**Issue by vinitkumar** [vinitkumar/node-twitter#216]
https://sentry.io/gotchacode/node-twitter/issues/527589781/

```
TypeError: Cannot set property 'github' of null
  File "/app/config/passport.js", line 71, in null.<anonymous>
    user.github = profile._json;

TypeError: Cannot set property 'github' of null
```

**Comment by vinitkumar** [comment]
@robertcoopercode Did your username changed recently? I can see the error but can't reproduce the issue. Since you can see the line of crash, you can easily fix it I think.

**Comment by robertcoopercode** [comment]
Ah, it probably has to do with a changed Github username like you suggested.
