### ISSUE TITLE
Allow user to delete their account and related data

### ISSUE THREAD

**Issue by vinitkumar** [vinitkumar/node-twitter#223]
**Is your feature request related to a problem? Please describe.**
Some users use their own github account(in some cases work). They might want to delete their user account.

**Describe the solution you'd like**

Implement delete functionality like this:
- In user profile, provide a delete button.
- The button on click leads to a confirm dialog and then on click, the user data is deleted, user's related object is deleted(posts, comments)
- Once deleted the users' uuid should not return a 404.

**Comment by robertcoopercode** [comment]
Sounds like a good feature 👍 People like having the option to delete their data these days.
