### ISSUE TITLE
Internal server error on pagination

### ISSUE THREAD

**Issue by arjunans** [vinitkumar/node-twitter#226]
**Describe the bug**
On clicking the last page in pagination throws internal server error.

**To Reproduce**
1. Login into application
2. Click on the last page in the pagination
It will show a message "Internal server error"
**Expected behavior**
Should display tweets

**Screenshots**
![internal server error](https://user-images.githubusercontent.com/15280629/47401702-0ffef700-d760-11e8-9e69-1245c1a8399b.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome latest version

**Comment by vinitkumar** [comment]
This is fixed
