### ISSUE TITLE
Dancing licenses? MIT -> BSD ->GPL3 ?

### ISSUE THREAD

**Issue by RobertoMalatesta** [vinitkumar/node-twitter#228]
Hi @vinitkumar ,
the project in itself is very interesting, but my advice is to choose a less chocking license than GPL3 or AGPL:
Those licenses are a real nightmare to deal with when mixing projects and are seen as the black plague in the enterprise field.
I seem to recall this project was MIT (a friendly license).
If you switched for attribution reasons you might consider the Apache Public License (that preserves Copyright Info).

Just my 2 cents.

Roberto

**Comment by vinitkumar** [comment]
@RobertoMalatesta I think you are right. I will think about making it Apache.
Thanks for the feedback. 👍

**Comment by vinitkumar** [comment]
@RobertoMalatesta License is now going to be Apache Public license. I did the change and it is the default now. 

Thanks for your inputs again.

**Comment by RobertoMalatesta** [comment]
Superb.
Now my eyes are not legally blind anymore and I can look at the code :smiley: 

-R

**Comment by vinitkumar** [comment]
@RobertoMalatesta Feel free to contribute to the code as well.

**Comment by vinitkumar** [comment]
@RobertoMalatesta I do have this https://github.com/vinitkumar/node-twitter#important. Not sure if that's enough.
