### ISSUE TITLE
Pure 100% NodeJS application without MongoDB ?

### ISSUE THREAD

**Issue by RobertoMalatesta** [vinitkumar/node-twitter#230]
Hi @vinitkumar ,
can you consider the advantages of taking out MongoDB, replacing/optioning it with something similar like NeDB or TingoDB to reduce external non-node dependencies ?

The first advantage that comes to mind is using pkg on it to produce a standalone executable for Linux/Mac/Win with a single command.

Installation will be zero time for anyone, even unskilled users.

--R

**Comment by vinitkumar** [comment]
@RobertoMalatesta This is the first time hearing about TingoDB/NeDB. I will look into them and will get back to you. 
> Installation will be zero time for anyone, even unskilled users.
This Sounds excellent, will have to deep dive into it.
