### ISSUE TITLE
[FEATURE] Setup with docker

### ISSUE THREAD

**Issue by vinitkumar** [vinitkumar/node-twitter#236]
**Is your feature request related to a problem? Please describe.**
The project doesn't support docker yet. It might make things difficult for some users since it requires manual installation of the software.

**Describe the solution you'd like**
Automate setup and build using docker and docker-compose

**Describe alternatives you've considered**
None

**Comment by vinitkumar** [comment]
- https://nodejs.org/es/docs/guides/nodejs-docker-webapp/

**Comment by irsol** [comment]
@vinitkumar does my pull request solve this issue with Docker?
