### ISSUE TITLE
[BUG] Server Discovery and Monitoring engine is deprecated

### ISSUE THREAD

**Issue by irsol** [vinitkumar/node-twitter#249]
**Describe the bug**

Mongoose sends this Deprecation Warning: 

`(node:30) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.`

**To Reproduce**

`docker-compose --log-level DEBUG build web`

`docker-compose run --service-ports web`

**Comment by vinitkumar** [comment]
@irsol Thanks for reporting this. We need to upgrade mongoose for this project. But it is a breaking change and I would like to do it in one PR that only deals with this upgrade.

**Comment by irsol** [comment]
@vinitkumar mongoose was upgraded to version "mongoose": "5.7.5" and Deprecation Warning disappeared. After the pull request was merged shall we close this issue #249?

**Comment by vinitkumar** [comment]
@irsol Yes.
