### ISSUE TITLE
[FEATURE] Move secrets to .env file 

### ISSUE THREAD

**Issue by irsol** [vinitkumar/node-twitter#252]
**Describe the solution you'd like**
Add secrets to a `.env` file in the project root folder and add `.env` to `.gitignore` file, so it will never be committed. It helps to avoid stealing github and other secrets.

**Comment by vinitkumar** [comment]
@irsol Thanks for reporting this. Let's do the improvements in smaller PRs. It helps in reviewing and ensuring everything still works.

**Comment by irsol** [comment]
@vinitkumar tests still don't work. I can create a new branch or work in my forked repo and create new pull request from there. Which way would you prefer?

**Comment by vinitkumar** [comment]
Can you access the associated  travis env to see what is missing? I think
it is because of env variables you moved but they are not declared in the
travis.

**Comment by irsol** [comment]
@vinitkumar I added all needed env variables to Travis and opened new pull request which will fix all issues with tests. https://github.com/vinitkumar/node-twitter/pull/263

**Comment by irsol** [comment]
@vinitkumar all tests passed in my branch https://travis-ci.org/irsol/node-twitter/builds/617127398

**Comment by vinitkumar** [comment]
@irsol thanks for the effort. However, looks like you added the env variable in your own fork and not this main upstream travis. Could you please update the env variables and their values here? I will update them to to the project and restart the build. Or you can try setting them directly here (https://travis-ci.org/vinitkumar/node-twitter?utm_medium=notification). Let me know if you are able to do this?

**Comment by irsol** [comment]
the variables are already there. But I still can not build develop branch.

**Comment by vinitkumar** [comment]
Anyways, I will merge your PR and fix the issues with CI later.

**Comment by irsol** [comment]
I will also look at the issue.

**Comment by irsol** [comment]
All tests passed after the merge.
