### ISSUE TITLE
[BUG] Login Broken After Issue #252 merge

### ISSUE THREAD

**Issue by vinitkumar** [vinitkumar/node-twitter#265]
Try and login to the server using Github. Github sends a 404 and never redirects. @irsol I think your code might have broken something. Could you please check it out. Also, please check your code while sending PR(basic actions like login, logout, tweeting, commenting etc)

Please send a PR to `develop` when done.

**Comment by irsol** [comment]
@vinitkumar I'm on it. It doesn't work locally or via Docker?

**Comment by vinitkumar** [comment]
It doesn't work anywhere..

**Comment by irsol** [comment]
Next I will check everything before creating pull request.

**Comment by vinitkumar** [comment]
@irsol Thanks, it's generally a good practice to do some basic sanity tests when making a PR. Also, don't worry much about it. It happens to everyone.  Another key here is to make small Pull Requests that do very limited things, those are easier to test and hence container fewer bugs/less-severe bugs.

**Comment by irsol** [comment]
@vinitkumar  to make it work you need to set your GITHUB_CLIENT_SECRET and GITHUB_CLIENT_ID in your local .env file. It was the main idea to remove secrets from git and allow everyone to use own secrets locally.

**Comment by vinitkumar** [comment]
@irsol Okay, found the bug. The keys were reverted in the config for production. Check this commit. https://github.com/vinitkumar/node-twitter/commit/bb2f18e2652aad3b93024624006beb237eba5731
