### ISSUE TITLE
[FEATURE] Implement hashtags

### ISSUE THREAD

**Issue by irsol** [vinitkumar/node-twitter#268]
## Feature

A hashtag is a word or phrase following after a pound symbol `#`. After adding a hashtag in your tweet that hashtag will become highlighted and clickable for the reader.

It allows to index keywords or topics on Twitter and helps people to easily follow topics they are interested in.  

Clicking on a hashtagged word in tweet shows you other Tweets that include that hashtag: [nodejs](https://twitter.com/hashtag/nodejs?src=hash&lang=en).

## Expected behaviour 

1. When user adds a hashtag to a tweet, the hashtag becomes clickable and highlighted.
2. Clickable means: a hashtag links to a group of posts using the same hashtag. 
URL format: `http://<server_url>/hashtag/<hashtag_string>`
3. When user clicks it shows: all the tweets that mention the hashtag in real time.
4. Hashtag must be a string without spaces.

**Comment by vinitkumar** [comment]
@irsol Great idea. I had this in mind since long but never found enough time. Do you want to implement this one or have a working PR. Let me know?

**Comment by irsol** [comment]
@vinitkumar yes, I want to implement. ) I start from #269 and this feature will be next.

**Comment by vinitkumar** [comment]
@irsol Awesome. Please let me know if you need any help. Some tips:

- write the design doc in the code first, outlining what and how you want to do and then proceed to write the code. This should probably be the first commit.
- make small, readable commits
- don't try to do a lot of things at once and do it in a systematic way.
- Write clean and simple code and improvise things later. 

All the best  👍

**Comment by irsol** [comment]
@vinitkumar thank you!

**Comment by vinitkumar** [comment]
@irsol Are you working on this at the moment? If yes, are there any issues implementing this? Please let me know.

**Comment by irsol** [comment]
@vinitkumar I'm working on it. I'm planing to finish this task till Monday.

**Comment by vinitkumar** [comment]
Don't worry about it
Also, make a PR even for work in progress stuff. It helps to identify
design flaws. Just add a WIP in the title.

**Comment by irsol** [comment]
@vinitkumar finally, we can close it.😃

**Comment by vinitkumar** [comment]
Yes.

**Comment by vinitkumar** [comment]
@irsol Some updates:

You missed a minor detail, the hashtag should be made a link with `#` in front of the link. I corrected it with this small commit. https://github.com/vinitkumar/node-twitter/commit/755f09e7287a22e5aabaa9a87398bfba3a472a4f

Also, the footer is now changed and attributes to all the contributors of Node Twitter (you included).

Here are some screenshots for the same.
![Screenshot 2020-01-07 at 5 21 03 PM](https://user-images.githubusercontent.com/537678/71893766-88d64d00-3172-11ea-8cf5-8a6a565e73c9.png)
![Screenshot 2020-01-07 at 5 21 14 PM](https://user-images.githubusercontent.com/537678/71893768-896ee380-3172-11ea-8f4b-834c0616d467.png)


Please let me know what you think about this. 🍺

**Comment by irsol** [comment]
@vinitkumar🎉cool!
