### ISSUE TITLE
Node Twitter redesign goals

### ISSUE THREAD

**Issue by vinitkumar** [vinitkumar/node-twitter#84]
- [ ] Built on top of latest express
- [ ] Use mongoose mostly for schema design.
- [ ] Error caching, exception handling.
- [ ] Well documented API
- [x] Tests integrations with Travis/wercker
- [ ] Built on bootstrap 4
- [ ] More Twitter like functionality (Decide on this one)

**Comment by vinitkumar** [comment]
## High level Goals

- Build Messages features.
- Build Follow, Unfollow feature.
- Add more details to user profile.

**Comment by vinitkumar** [comment]
Follow, unfollow works now.

**Comment by Engineering-Robert** [comment]
@vinitkumar Can we break up any of these into their own issues? The Bootstrap 4 migration is already marked as an issue.

**Comment by vinitkumar** [comment]
@Engineering-Robert Yes. Feel free to do so.

**Comment by Engineering-Robert** [comment]
Cool
