### ISSUE TITLE
Build one to one messaging

### ISSUE THREAD

**Issue by vinitkumar** [vinitkumar/node-twitter#98]
Sample Model code

```js
const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const MessageSchema = new Schema({
  message: { type: String, default: "", trim: true, maxlength: 200},
  sender: { type: Schema.ObjectId, ref: "User" },
  reciever: { type: Schema.ObjectId, ref: "User" }, 
  createdAt: { type: Date, default: Date.now },
});
```
So the idea here is that, we store the message, and time as well the users. And when you look at the chat window, it will basically find all chat between the sender and receiver.

**Comment by vinitkumar** [comment]
Sample Model code

```js
const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const MessageSchema = new Schema({
  message: String,
  sender: { type: Schema.ObjectId, ref: "User" },
  reciever: { type: Schema.ObjectId, ref: "User" }, 
  createdAt: { type: Date, default: Date.now },
});
```
So the idea here is that, we store the message, and time as well the users. And when you look at the chat window, it will basically find all chat between the sender and receiver.

**Comment by Engineering-Robert** [comment]
@vinitkumar Is this feature still being worked on? I know I've got to fix some styling related to the messaging features, but are you still improving on the functionality?

**Comment by vinitkumar** [comment]
Too old issue. Will make a new one for new functionalities.
